substitutions:
  _REGION: "us-central1"
  _RUNTIME: "python312"
  _REQ_TOPIC: "edgarai-request"
  _RES_TOPIC: "edgarai-response"
  _BUCKET_ID: "edgar_666"
  _LOG_LEVEL: "INFO"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "functions"
      - "deploy"
      - "edgar_processor"
      - "--gen2"
      - "--region=${_REGION}"
      - "--runtime=${_RUNTIME}"
      - "--memory=2G"
      - "--timeout=1800s"
      - "--max-instances=200"
      - "--trigger-topic=${_REQ_TOPIC}"
      - "--entry-point=edgar_processor"
      - "--source"
      - "."
      - "--set-env-vars"
      - "GCS_BUCKET_ID=${_BUCKET_ID},RESPONSE_TOPIC=${_RES_TOPIC},LOG_LEVEL=${_LOG_LEVEL}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "functions"
      - "deploy"
      - "trigger_processor"
      - "--gen2"
      - "--region=${_REGION}"
      - "--runtime=${_RUNTIME}"
      - "--memory=1G"
      - "--trigger-http"
      - "--no-allow-unauthenticated"
      - "--entry-point=trigger_processor"
      - "--source"
      - "."
      - "--set-env-vars"
      - "GCS_BUCKET_ID=${_BUCKET_ID},REQUEST_TOPIC=${_REQ_TOPIC},RESPONSE_TOPIC=${_RES_TOPIC},LOG_LEVEL=${_LOG_LEVEL}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "functions"
      - "deploy"
      - "get_most_relevant_chunks"
      - "--gen2"
      - "--region=${_REGION}"
      - "--runtime=${_RUNTIME}"
      - "--timeout=120s"
      - "--max-instances=100"
      - "--trigger-http"
      - "--no-allow-unauthenticated"
      - "--entry-point=get_most_relevant_chunks"
      - "--source"
      - "."
      - "--set-env-vars"
      - "LOG_LEVEL=${_LOG_LEVEL}"
